# Generated by Django 5.2.6 on 2025-12-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_remove_cliente_idarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                ("idServicio", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipoServicio",
                    models.CharField(
                        choices=[
                            ("PC", "Reparación de Computador"),
                            ("IMP", "Reparación de Impresora"),
                            ("TON", "Recarga de Tóner"),
                        ],
                        max_length=3,
                    ),
                ),
                ("fechaIngreso", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REC", "Recibido"),
                            ("PRO", "En proceso"),
                            ("TER", "Terminado"),
                            ("ENT", "Entregado"),
                            ("NRE", "No realizado"),
                        ],
                        default="REC",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "valorServicio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="idCliente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicios",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReparacionPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        help_text="Número de serie del equipo",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("problema", models.TextField()),
                ("solucion", models.TextField(blank=True, null=True)),
                (
                    "servicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc",
                        to="servicios.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReparacionImpresora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        help_text="Número de serie de la impresora",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("falla", models.TextField()),
                ("solucion", models.TextField(blank=True, null=True)),
                (
                    "servicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impresora",
                        to="servicios.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecargaToner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo_toner", models.CharField(max_length=100)),
                (
                    "servicio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.servicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                ("idAbono", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="servicios.servicio",
                    ),
                ),
            ],
        ),
    ]
