# Generated by Django 6.0.5 on 2026-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacionimpresora',
            name='falla',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacionpc',
            name='problema',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacionpc',
            name='solucion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('REC', 'Recibido'), ('PRO', 'En proceso'), ('TER', 'Terminado'), ('ENT', 'Entregado'), ('NRE', 'No realizado'), ('GAR', 'Garantía')], default='REC', max_length=100),
        ),
    ]
