# Generated by Django 6.0.5 on 2026-08-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_reparacionimpresora_falla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fechaEntrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
