# Generated by Django 5.2.6 on 2025-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('idArea', models.IntegerField()),
                ('tipoDocumento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('numeroDocumento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
