# Generated by Django 5.2.6 on 2025-10-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idArea',
        ),
    ]
